spring:
  h2:    console:      path: /console
      enabled: true
  application:
    name: spring-cloud-eureka-client
    
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
